apiVersion: v1
kind: Service
metadata:
  name: headscale
  labels:
    app: headscale
    role: control
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: headscale
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: http-acme
      port: 80
      targetPort: 80
      protocol: TCP
